### PR TITLE
Ruby Capstone Project PR

### PR DESCRIPTION
**Pull request by mertkantaroglu**
Hello,

In this project me, @batoorsohail, @lugard1 and @Nezerwa worked together.

In the project we added below functions;

#### Logic

- Each class from the [UML class diagram] were created in a separate .rb file.
- All associations (1-to-many relationships) and aggregations (parent-child relationships) between classes are implemented.
- All properties visible in the diagram are defined and set up in the constructor method. 
- All methods visible in the diagram are implemented:
    - add_item method (in all classes that have that method)
        - takes an instance of the Item class as an input.
        - adds the input item to the collection of items.
        - adds self as a property of the item object (by using the correct setter from the item object).
    - can_be_archived?() in the Item class
        - returns true if published_date is older than 10 years.
        - otherwise, it returns false.
    - move_to_archive() in the Item class
        - reuses can_be_archived?() method.
        - changes the archived property to true if the result of the can_be_archived?() method is true.
        - does nothing if the result of the can_be_archived?() method is false.
    - can_be_archived?() in the Book class
        - overrides the method from the parent class.
        - returns true if parent's method returns true OR if cover_state equals to "bad".
        - otherwise, it returns false.
    - can_be_archived?() in the MusicAlbum class
        - overrides the method from the parent class.
        - returns true if parent's method returns true AND if on_spotify equals true.
        - otherwise, it returns false.
    - can_be_archived?() in the Movie class
        - overrides the method from the parent class.
        - returns true if parent's method returns true OR if silent equals true.
        - otherwise, it returns false.
    - can_be_archived?() in the Game class
        - overrides the method from the parent class.
        - returns true if parent's method returns true AND if last_played_at is older than 2 years.
        - otherwise, it returns false.
- Added unit tests for all implemented methods.

#### User interface

- Created a main.rb file that serves as console app entry-point.
- Our console app, at the start:
    - Presents the user with a list of options to perform.
    - Lets users choose an option.
    - If needed, asks for parameters for the option.
    - Has a way to quit the app.
- The following options are also available:
    - List all books
    - List all music albums
    - List all movies
    - List of games
    - List all genres (e.g 'Comedy', 'Thriller')
    - List all labels (e.g. 'Gift', 'New')
    - List all authors (e.g. 'Stephen King')
    - List all sources (e.g. 'From a friend', 'Online shop')
    - Add a book
    - Add a music album
    - Add a movie
    - Add a game
 - All data are preserved by saving collections in .json files.

### Database
- Created a schema.sql file with tables that will be analogical to the structure of the classes in our app. As we could not implement inheritance in the database tables - added all properties and associations from the parent Item class as table columns to all tables based on the child classes. Thanks to that it can be used to store data in the future.

- Added presentation video.

Looking forward to hearing from you.

Thanks.

### CODE REVIEW

**Review by elisha2kyakpo1 — CHANGES_REQUESTED** [review]
Hi 👋 team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

👏 You did it guys. You have a very nice UI making it easy for me to do my work.

✔️ The PR title and description are good and professional.
✔️ No linter errors.
✔️ Descriptive readme file.
✔️ Tests passing👏
👏 The app works as expected.

## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly record a video as per the project requirements. I have attached a screenshot for your reference about the video requirements.

video


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mertkantaroglu** [comment]
Thanks @elisha2kyakpo1 👍

**Review by omarsalem7 — APPROVED** [review]
Hi team 😊, 
# STATUS: APPROVED! 🥇 💯 



Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀 
Congratulations! 🎉 

## Highlights
✅ Great presentation demo
✅ Project has met all the technical aspects you needed for this project. Keep rocking! 

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mertkantaroglu** [comment]
Thank you very much @omarsalem7 👍

**Pull request merged**
